eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8090
  
spring:
  application:
    name: smkt-gateway
  cloud:
    gateway:
     discovery:
        locator:
          enabled: true
     
     globalcors:
        cors-configurations:
          '[/**]':
             allowedOrigins : "*"
             allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - HEAD
     routes:
     
      - id: smkt-pantry
        uri: lb://smkt-pantry
        predicates:
          - Path=/smkt-p/**
        filters:
          - RewritePath=/smkt-p/(?<path>.*), /$\{path}
        
      - id: smkt-cookbook
        uri: lb://smkt-cookbook
        predicates:
          - Path=/smkt-c/**
        filters:
          - RewritePath=/smkt-c/(?<path>.*), /$\{path}
        
      - id: smkt-oauth
        uri: lb://smkt-oauth
        predicates:
          - Path=/smkt-a/**
        filters:
          - RewritePath=/smkt-a/(?<path>.*), /$\{path}
        
      - id: smkt-users
        uri: lb://smkt-users
        predicates:
          - Path=/smkt-u/**
        filters:
          - RewritePath=/smkt-u/(?<path>.*), /$\{path}
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG
