eureka:
  client:
    service-url:
      defaultZone: http://172.0.0.3:8761/eureka
server:
  port: 8090
  
spring:
  application:
    name: smkt-gateway
  cloud:
    gateway:
     discovery:
        locator:
          enabled: true
     routes:
      - id: smkt-kitchen
        uri: lb://smkt-kitchen
        predicates:
        - Path=/kitchen/**
        filters:
        - RewritePath=/kitchen/(?<path>.*), /$\{path}
