eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8090
  
spring:
  application:
    name: smkt-gateway
  cloud:
    gateway:
     
     discovery:
        locator:
          enabled: true
     
     globalcors:
        cors-configurations:
          '[/**]':
             allowedOrigins : "*"
             allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - HEAD
     routes:
      - 
        id: smkt-pantry
        uri: lb://smkt-pantry
        predicates:
        - Path=/pantry/**
        filters:
        - RewritePath=/pantry/(?<path>.*), /$\{path}
        
      - 
        id: smkt-cookbook
        uri: lb://smkt-cookbook
        predicates:
        - Path=/cookbook/**
        filters:
        - RewritePath=/cookbook/(?<path>.*), /$\{path}
        
      - 
      
        id: smkt-oauth
        uri: lb://smkt-oauth
        predicates:
        - Path=/auth/**
        filters:
        - RewritePath=/auth/(?<path>.*), /$\{path}
        
      - 
        id: smkt-users
        uri: lb://smkt-users
        predicates:
        - Path=/users/**
        filters:
        - RewritePath=/users/(?<path>.*), /$\{path}
        