eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8090
  
spring:
  application:
    name: smkt-gateway
  cloud:
    gateway:
     discovery:
        locator:
          enabled: true
     routes:
      - id: smkt-kitchen
        uri: lb://smkt-kitchen
        predicates:
        - Path=/kitchen/**
        filters:
        - RewritePath=/kitchen/(?<path>.*), /$\{path}
      - id: smkt-oauth
        uri: lb://smkt-oauth
        predicates:
        - Path=/auth/**
        filters:
        - RewritePath=/auth/(?<path>.*), /$\{path}
        